ranks = {
    'root cl.': {
        'id': 1,
        'level': 1,
        'name': 'Root clade',
        'latin_name': 'Radix cladus',
        'abbreviation': 'root cl.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'regn.': {
        'id': 2,
        'level': 2,
        'name': 'Kingdom',
        'latin_name': 'Regnum',
        'abbreviation': 'regn.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subregn.': {
        'id': 3,
        'level': 3,
        'name': 'Subkingdom',
        'latin_name': 'Subregnum',
        'abbreviation': 'subregn.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'div.': {
        'id': 4,
        'level': 4,
        'name': 'Division',
        'latin_name': 'Divisio',
        'abbreviation': 'div.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subdiv.': {
        'id': 5,
        'level': 5,
        'name': 'Subdivision',
        'latin_name': 'Subdivisio',
        'abbreviation': 'subdiv.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'cl.': {
        'id': 6,
        'level': 6,
        'name': 'Class',
        'latin_name': 'Classis',
        'abbreviation': 'cl.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subcl.': {
        'id': 7,
        'level': 7,
        'name': 'Subclass',
        'latin_name': 'Subclassis',
        'abbreviation': 'subcl.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'ord.': {
        'id': 8,
        'level': 8,
        'name': 'Order',
        'latin_name': 'Ordo',
        'abbreviation': 'ord.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subord.': {
        'id': 9,
        'level': 9,
        'name': 'Suborder',
        'latin_name': 'Subordo',
        'abbreviation': 'subord.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'fam.': {
        'id': 10,
        'level': 10,
        'name': 'Family',
        'latin_name': 'Familia',
        'abbreviation': 'fam.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subfam.': {
        'id': 11,
        'level': 11,
        'name': 'Subfamily',
        'latin_name': 'Subfamilia',
        'abbreviation': 'subfam.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'tr.': {
        'id': 12,
        'level': 12,
        'name': 'Tribe',
        'latin_name': 'Tribus',
        'abbreviation': 'tr.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subtr.': {
        'id': 13,
        'level': 13,
        'name': 'Subtribe',
        'latin_name': 'Subtribus',
        'abbreviation': 'subtr.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'gen.': {
        'id': 14,
        'level': 14,
        'name': 'Genus',
        'latin_name': 'Genus',
        'abbreviation': 'gen.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'nothogen.': {
        'id': 15,
        'level': 14,
        'name': 'Nothogenus',
        'latin_name': 'Nothogenus',
        'abbreviation': 'nothogen.',
        'prefix': '×',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subgen.': {
        'id': 16,
        'level': 15,
        'name': 'Subgenus',
        'latin_name': 'Subgenus',
        'abbreviation': 'subgen.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'sect.': {
        'id': 17,
        'level': 16,
        'name': 'Section',
        'latin_name': 'Sectio',
        'abbreviation': 'sect.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subsect.': {
        'id': 18,
        'level': 17,
        'name': 'Subsection',
        'latin_name': 'Subsectio',
        'abbreviation': 'subsect.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'ser.': {
        'id': 19,
        'level': 18,
        'name': 'Series',
        'latin_name': 'Series',
        'abbreviation': 'ser.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'subser.': {
        'id': 20,
        'level': 19,
        'name': 'Subseries',
        'latin_name': 'Series',
        'abbreviation': 'ser.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'sp.': {
        'id': 21,
        'level': 20,
        'name': 'Species',
        'latin_name': 'Species',
        'abbreviation': 'sp.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': '',
    },
    'nothosp.': {
        'id': 22,
        'level': 20,
        'name': 'Nothospecies',
        'latin_name': 'Nothospecies',
        'abbreviation': 'nothosp.',
        'prefix': '',
        'interfix': '×',
        'infraspecific_interfix': '',
    },
    'subsp.': {
        'id': 23,
        'level': 21,
        'name': 'Subspecies',
        'latin_name': 'Subspecies',
        'abbreviation': 'subsp.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': 'ssp.',
    },
    'var.': {
        'id': 24,
        'level': 21,
        'name': 'Variety',
        'latin_name': 'Varietas',
        'abbreviation': 'var.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': 'var.',
    },
    'subvar.': {
        'id': 24,
        'level': 21,
        'name': 'Subvariety',
        'latin_name': 'Subvarietas',
        'abbreviation': 'subvar.',
        'prefix': '',
        'interfix': 'subvar.',
        'infraspecific_interfix': 'subvar.',
    },
    'f.': {
        'id': 22,
        'level': 21,
        'name': 'Form',
        'latin_name': 'Forma',
        'abbreviation': 'f.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': 'f.',
    },
    'subf.': {
        'id': 22,
        'level': 21,
        'name': 'Subform',
        'latin_name': 'Subforma',
        'abbreviation': 'subf.',
        'prefix': '',
        'interfix': '',
        'infraspecific_interfix': 'subf.',
    },
}